### ISSUE TITLE
DOMDocument::loadHTML(): Empty string supplied as input

### ISSUE THREAD

**Issue by ghost** [terrylinooo/CodeIgniter-Minifier#4]
I found the issues after minified the code if calling ajax return json will hit the error  DOMDocument::loadHTML(): Empty string supplied as input. 

**Severity: Warning
Message:  DOMDocument::loadHTML(): Empty string supplied as input
Filename: libraries/CI_Minifier.php
Line Number: 196**

Below is the screenshot of network response:

![screenshot_2](https://cloud.githubusercontent.com/assets/1627923/19877968/d4321092-a01e-11e6-8476-8af10c437cc8.png)

**Comment by terrylinooo** [comment]
It seems like $CI->output->get_output();  doesn't work with JSON. I have no idea about this because it is CI core API.

**Comment by terrylinooo** [comment]
After testing on my side, I didn't notice such kind problem. 

`Message: DOMDocument::loadHTML(): Empty string supplied as input` 
It is because that $CI->output->get_output(); received empty string.

Here is the document you can read in **get_output()** section:
http://www.codeigniter.com/userguide3/libraries/output.html

> Note that data will only be retrievable from this function if it has been previously sent to the output class by one of the CodeIgniter functions like $this->load->view().
